apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xot6ehijr-go 
  janus-idp.io/tekton: xot6ehijr-go
  backstage.io/kubernetes-id: xot6ehijr-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xot6ehijr-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml